import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import { useState } from 'react'
import {BsSearch} from 'react-icons/bs'
import Weather from '@/components/Weather'
import Spinner from '@/components/Spinner'
import urlExist from 'url-exist';






export default function Home() {

const[city, setCity] = useState('')
const[weather, setWeather] = useState({})
const[loading, setLoading] = useState(false)

   const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WHEATHER_KEY}`
 
   const fetchWeather =  async (e) =>{
    e.preventDefault()
    setLoading(true)
   

    const exists = await urlExist(url);
    console.log(exists);
    exists ? city != '' ? axios.get(url).then((response) => {
setWeather(response.data) }):  console.log("no data") :console.error("there is no city called " + city)
//console.log(respose.data)
    
    setCity('')
    setLoading(false)
  }
  if(loading){
return ( <Spinner/>)
  }
  else{
   return (
    <div>
      <Head>
        <title> Wheather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Overlay */}
      <div className ='absolute top-0 left-0 bottom-0 bg-black/40 z-[1]'/>
<Image alt="/" src='https://images.unsplash.com/photo-1557170308-24e08d78ff53?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80' layout='fill'
className = 'object-cover' />


     {/* Search */}
     <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
      <form onSubmit={fetchWeather} className=" flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl">
      <div>
        <input onChange={(e)=>setCity(e.target.value)} className=' bg-transparent border-none text-white focus:outline-none text-2xl' type="text" placeholder='Search city' />
        </div>
          <button onClick={fetchWeather}><BsSearch size={20}/>
          </button>
       
      </form>
     </div>
 {/* Display Weather Data */}
 {weather.main && <Weather data={weather} />}
    </div>
  )
}
}


